title: Tajemství K-popu
baseURL: https://amazing-nightingale-44bd22.netlify.com/
languageCode: cs-cz
publishDir: public

menu:
  main:
    - name: Homepage
      url: /
      weight: 10
    - name: Archive
      identifier: post
      url: /post/
      weight: 20

params:
  description: Stránka zabývající se K-popem a jeho vzrůstající popularitou.
  authors: Hana Jakubčíková, Kamila Vejmelková

